class racksheetV1Appmod
{
    url := "http://asag.windstream.com/apps/racksheets/LogIn/login.asp"
	uname := ["fe","name","uname"]
	pword := ["fe","name","pword"]
	submitButton := ["fe","name","cmdSubmit"]
    stateFrame := ["fe","name","contents"]
	submitForm := ["fe","xpath","/html/body/ul[1]/li[1]/b/a"]
    selectStateFrame := ["fe","name","main"]
	racstate := ["fe","xpath","/html/body/div/center/table/tbody/tr[1]/td/center/b"]
	raccity := ["fe","name","exchange"]
	svcOrder := ["fe","name","order_info"]
	picIpic := ["fe","name","PicIpic"]
	boid := ["fe","name","BOID"]
	duedate := ["fe","name","duedate"]
	winback := ["fe","name","Winback"]
	techcall := ["fe","name","TechCall"]
	dcrisstatus := ["fe","name","FieldVisit"]
	TeleNumIn := ["fe","name","TeleNumIN"]
	TeleNumOut := ["fe","name","TeleNumOUT"]
	GradeIn := ["fe","name","MirorGradeIN"]
	GradeOut := ["fe","name","MirorGradeOUT"]
	WirecenterIn := ["fe","name","MirorWCIN"]
	WirecenterOut := ["fe","name","MirorWCOUT"]
	CoeIn := ["fe","name","COEIN"]
	CoeOut := ["fe","name","COEOUT"]
	FeatureIn := ["fe","name","VMFeature"]
	FeatureOut := ["fe","name","VMFeatInOut"]
	MDFPairIn := ["fe","name","MDFPairIN"]
	MDFPairOut := ["fe","name","MDFPairOUT"]
	BlockPinIn := ["fe","name","Loop2BlkPinIN"]
	BlockPinOut := ["fe","name","Loop2BlkPinOUT"]
	FramePairIn := ["fe","name","FramePair1IN"]
	FramePairOut := ["fe","name","FramePair1OUT"]
	LineEquIn := ["fe","name","LineEquipIN"]
	LineEquOut := ["fe","name","LineEquipOUT"]
	Comment := ["fe","name","comments"]
	sendCo := ["fe","name","SendCO"]
	sendsag := ["fe","name","SendSag"]
	sendcomplex := ["fe","name","SendTech"]
	lastSeg := ["fe","name","LastSegment"]
	lastSubmitButton := ["fe","name","submit"]
	;~ clickHere := ["fe","xpath","/html/body/p[5]/span/a"]
	clickHere := ["fe","xpath","//*[contains(text(),'To view/update all segments of last Racksheet entered click here')]"]
	racksheetframe1 := ["fe","xpath","/html/frameset"]
	racksheetframe2 := ["fe","xpath","/html//html/frameset/frameset"]
	racksheetFrame := ["fe","name","main"]
	racksheetSubmit := ["fe","xpath","/html/body/table[3]/tbody/tr[2]/td[3]/center/table/tbody/tr/td/center/a"]
}




